//------------------------------------------------------------------------------
//	Copyright ©1996 qualia, inc. All rights reserved.
//
//	Written by:			Bretton Wade
//	Last Revision:	03/19/96
//
//------------------------------------------------------------------------------

#ifndef	DEFINE_PI
#define	DEFINE_PI

//------------------------------------------------------------------------------
void	DefinePI (void);																													//	fill in the definitions of PI

//------------------------------------------------------------------------------
extern	Real	PI;																																//	3.14
extern	Real	OVER_PI;																													//	3.14
extern	Real	TWO_PI;																														//	6.28
extern	Real	OVER_TWO_PI;																											//	0.16
extern	Real	PI_OVER_TWO;																											//	1.57

//------------------------------------------------------------------------------

#endif	//	DEFINE_PI