//------------------------------------------------------------------------------
//	Copyright ©1995 qualia, inc. All rights reserved.
//
//	This code may not be copied or used in any way without the expressed
//	written permission of qualia, inc. Any violation will be prosecuted
//	to the full extent of the law.
//
//	Written by:	Bretton Wade
//
//	Last Revised: 12/29/96
//
//------------------------------------------------------------------------------

#ifndef	PIXEL
#define	PIXEL

//------------------------------------------------------------------------------
#ifdef	EIGHTBITCOLOR
#include "pixel8.h"
#elif		SIXTEENBITCOLOR
#include "pixel16.h"
#endif

//------------------------------------------------------------------------------

#endif	//	PIXEL