//------------------------------------------------------------------------------
//	Copyright ©1996 qualia, inc. All rights reserved.
//
//	Written by:			Bretton Wade
//	Last Revision:	07/14/96
//
//------------------------------------------------------------------------------

#ifndef	TOKENIZE
#define	TOKENIZE

//------------------------------------------------------------------------------
int		Tokenize (cstr string, cstr *&array);																			//	process a string into a stream of tokens

//------------------------------------------------------------------------------

#endif	//TOKENIZE
