//------------------------------------------------------------------------------
//	Copyright ©1996-97 qualia, inc. All rights reserved.
//
//	Written by:			Bretton Wade
//	Last Revision:	01/06/97
//
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
#ifdef	_MSC_VER
#include "precompile.h"
#endif

//------------------------------------------------------------------------------
#include "sequence.h"

//------------------------------------------------------------------------------
Sequence::~Sequence (void)																											//	destructor
{																																								//	begin
}																																								//	end

//------------------------------------------------------------------------------
void	Sequence::Reset (void)																										//	return the sequence to its starting state
{																																								//	begin
}																																								//	end

//------------------------------------------------------------------------------
int		Sequence::Width (void)																										//	return the width of the sequence
{																																								//	begin
	return 0;																																			//	default to 0
}																																								//	end

//------------------------------------------------------------------------------
int		Sequence::Height (void)																										//	return the height of the sequence
{																																								//	begin
	return 0;																																			//	default to 0
}																																								//	end

//------------------------------------------------------------------------------
